### ISSUE TITLE
[Feature] JMatrix do not have a `!=` and a `==` Operator

### ISSUE THREAD

**Issue by MrScautHD** [notgiven688/jitterphysics2#105]
**Greetings!**

I'm eager to propose the inclusion of `!=` and `==` operators within JMatrix. This addition would greatly benefit not only myself but potentially many others as well.

**Comment by MrScautHD** [comment]
Im not needing it anymore.

**Comment by notgiven688** [comment]
This was "intentionally left out" of the implementation. Precise float-comparison can be tricky and should rarely be necessary. Consider for example

``
float a = 1.0f / 0.0f;
float b = 1.0f / 0.0f;

Console.WriteLine((a==b) ? "equal" : "not equal");

a = MathF.Sqrt(-1);
b = MathF.Sqrt(-1);

Console.WriteLine((a==b) ? "equal" : "not equal");
```
