### ISSUE TITLE
(Feature Request) Example NarrowPhaseFilter for adjacent voxels/JBoxes

### ISSUE THREAD

**Issue by captainkidd5** [notgiven688/jitterphysics2#108]
I don't have the necessary knowledge to implement it, but in the future it would be awesome to get a voxel version of 
[the ghost collision triangle mesh filter](https://github.com/notgiven688/jitterphysics2/blob/main/src/Jitter2/Collision/CollisionFilter/TriangleEdgeCollisionFilter.cs)

which prevents capsule shapes from snagging on internal edges of JBoxes placed adjacent to one another

**Comment by notgiven688** [comment]
Added a demo here: #123
