### ISSUE TITLE
ConvexHullShape with flat meshes

### ISSUE THREAD

**Issue by Khhs167** [notgiven688/jitterphysics2#111]
Hi! I'm currently working on implementing this library into my engine when I noticed I get an error whilst loading collision meshes.

Strange, I thought, so I had a look and found out that the issue lied in the fact that one of my collision meshes was simply a completely flat plane.

This then led to the mass calculations resulting in a mass of 0(since it's infinitely thin). And since 0 mass is disallowed it throws an error.

I'm wondering if there might be a fix available for this?

**Comment by notgiven688** [comment]
Thank you for reporting this. This sounds like a bug introduced with: https://github.com/notgiven688/jitterphysics2/commit/89d46a86489b0e09dab9deb072a4e8f45b371ec9

I guess you are creating static geometry and therefore do not care for the mass of the body?

**Comment by Khhs167** [comment]
I'm personally creating static geometry but I could imagine that's not the case for everyone who might experience this issue.

Also yes, it is that exact exception.

**Comment by notgiven688** [comment]
I think we can just remove the exception. It does not serve any purpose (any longer): https://github.com/notgiven688/jitterphysics2/pull/112
