### ISSUE TITLE
Issue debugging on linux (Ubuntu 22.04)

### ISSUE THREAD

**Issue by ClaudioPinho** [notgiven688/jitterphysics2#115]
I have been implementing the JitterPhysics2 with my own game engine using MonoGame but for some reason I am having problems debugging my game now, going step by step on the initialization process the debugger gets stuck somewhere inside the "World.Step" somewhere on the line "ThreadPool.Instance.SignalWait()".
I tried running the step without multi thread but it seems that the issue persists, however running the game normally without debugger has no issues, maybe this is happening since I am using linux but I tried using the older version of Jitter 1 and it runs well.

**Comment by notgiven688** [comment]
Noticed something similar, hence the "strange" comment here: https://github.com/notgiven688/jitterphysics2/blob/6f2aa228545c88c49a2f6b7208745ee6ba7b9863/src/Jitter2/Parallelization/ThreadPool.cs#L83

Do you have the DEBUG variable set, when debugging?

**Comment by notgiven688** [comment]
This probably should be a debug report for the debugger not this engine. I will investigate however. The other problem seems to be unrelated.

**Comment by notgiven688** [comment]
Cause of issue found in #174. Workaround needed.

**Comment by notgiven688** [comment]
Fixed (workaround implemented) in 2.4.4. Final fix with .NET 9.
