### ISSUE TITLE
Shapes passed to default narrow phase collision handler are not associated with a rigid body

### ISSUE THREAD

**Issue by labbbirder** [notgiven688/jitterphysics2#142]
I continuously spawning tiny size shapes, meanwhile, I remove the rigidbody in world randomly. Soon got a exception says `Shapes passed to default narrow phase collision handler are not associated with a rigid body`

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Shapes passed to default narrow phase collision handler are not associated with a rigid body.
  Source=Jitter2
  StackTrace:
   at Jitter2.World.Detect(Shape sA, Shape sB) in E:\UnityProjects\jitter2\src\Jitter2\World.Detect.cs:line 289
   at Jitter2.World.DetectCollisionsCallback(Batch batch) in E:\UnityProjects\jitter2\src\Jitter2\World.Step.cs:line 451
   at Jitter2.World.DetectCollisions(Boolean multiThread) in E:\UnityProjects\jitter2\src\Jitter2\World.Step.cs:line 764
   at Jitter2.World.Step(Single dt, Boolean multiThread) in E:\UnityProjects\jitter2\src\Jitter2\World.Step.cs:line 144
   at JitterDemo.Playground.Draw() in E:\UnityProjects\jitter2\src\JitterDemo\Playground.cs:line 127
   at JitterDemo.Renderer.OpenGL.GLFWWindow.Sync() in E:\UnityProjects\jitter2\src\JitterDemo\Renderer\OpenGL\GLFWWindow.cs:line 291
   at JitterDemo.Renderer.OpenGL.GLFWWindow.Open(CreationSettings settings) in E:\UnityProjects\jitter2\src\JitterDemo\Renderer\OpenGL\GLFWWindow.cs:line 179
   at JitterDemo.Program.Main() in E:\UnityProjects\jitter2\src\JitterDemo\Program.cs:line 25

```

Maybe it'a problem caused by DynamicTree.

I want to known why the tiny shapes so different, and how to solve the problems.

Here is the additional modification:
``` diff
...
        if (Keyboard.KeyPressBegin(Keyboard.Key.M))
        {
            multiThread = !multiThread;
        }

-        if (!GuiRenderer.WantsCaptureKeyboard && Keyboard.KeyPressBegin(Keyboard.Key.Space))
+        if (!GuiRenderer.WantsCaptureKeyboard && Keyboard.IsKeyDown(Keyboard.Key.Space))
        {
-            ShootPrimitive();
+            for (int i = 0; i < 2; i++)
+            {
+                ShootPrimitive();
+            }
        }
+        if (rand.Next(2) == 1)
+        {
+            var idx = rand.Next(world.RigidBodies.Count);
+            if (idx>4) world.Remove(world.RigidBodies[idx]);
+        }

         base.Draw();
...
```

_Originally posted by @labbbirder in https://github.com/notgiven688/jitterphysics2/issues/141#issuecomment-2138714138_

**Comment by labbbirder** [comment]
Here is a seperate issue from #141. To reproduct it:
* Edit the `Playerground.cs` as above mentioned, also change the size of spawned primite shape to a tiny number
* Run JitterDemo
* press and hold the space button for seconds

**Comment by notgiven688** [comment]
@labbbirder I have trouble reproducing this. Are you using v2.3.0 or the current master?

**Comment by labbbirder** [comment]
> @labbbirder I have trouble reproducing this. Are you using v2.3.0 or the current master?

It's a clone of commit 834cd43

**Comment by notgiven688** [comment]
@labbbirder Thank you. Will take a closer look later.

**Comment by notgiven688** [comment]
Unfortunately, I can not reproduce the exact crash. But I think we have a garbage-in-garbage-out situation. 

```
var ss = new BoxShape(rand.Next(1, 4) / 1000f);
```

produces shapes with about 1/1000 units in size. Mass is (1/1000) ^3 =1e-9 

Inertia is even worse:

inertia.M11 = 1.0f / 12.0f * mass * (size.Y * size.Y + size.Z * size.Z);
...

which is ~ 1e-9*(1e-6)=1-e15

and then you invert this matrix which just results in NaNs. We should guard against these by using more Debug.Asserts. But you can not expect Jitter with single precision floats to handle this.

Does the situation get better when you correct the mass properties?

```
sb.AddShape(ss);
sb.SetMassInertia(JMatrix.Identity, 1.0f);
```

Even if it does, the collision system is not made to handle shapes as  small as 1/1000 units (https://github.com/notgiven688/jitterphysics2/blob/main/src/Jitter2/Collision/NarrowPhase/ConvexPolytope.cs#L341).

**Comment by labbbirder** [comment]
@notgiven688 Thx for ur reply. 

I tried `sb.SetMassInertia(JMatrix.Identity, 1.0f);`, it doesn't work either. 

However, I have finally solved this problem. I'll post a PR later :)

**Comment by notgiven688** [comment]
@labbbirder Great! I am really curious now. Waiting for PR and/or more information :)

**Comment by labbbirder** [comment]
I switched the floating flags on the start of the World:
```csharp

    [DllImport("msvcrt.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint _control87(uint a, uint b);

    _control87(0x00080007, 0x0008001F);
```

Before the exception raises, I can see this floating overflow first.

**Comment by labbbirder** [comment]
> I think we found the same fix, nearly at the same time: #143 and #144

Yes. An awesome job :)

**Comment by notgiven688** [comment]
So, probably #141 was connected to this problem - as you have suspected from the beginning?

**Comment by labbbirder** [comment]
Yes. They result to be the same problem just as I suspected.
