### ISSUE TITLE
 Can a trigger be added, like Unity's collider?

### ISSUE THREAD

**Issue by long1752062104** [notgiven688/jitterphysics2#187]
Can a trigger be added, like Unity's collider?
I need to use triggers to do things like bullet flight, attack range triggers

**Comment by long1752062104** [comment]
> Can a trigger be added, like Unity's collider? I need to use triggers to do things like bullet flight, attack range triggers

Let's achieve it through this

public class TriggerCollisionDetection : IBroadPhaseFilter
{
    public bool Filter(IDynamicTreeProxy shapeA, IDynamicTreeProxy shapeB)
    {
        if (shapeA is not RigidBodyShape sA || shapeB is not RigidBodyShape sB)
        {
            throw new InvalidCollisionTypeException(shapeA.GetType(), shapeB.GetType());
        }

        ref RigidBodyData b1 = ref sA.RigidBody.Data;
        ref RigidBodyData b2 = ref sB.RigidBody.Data;

        if (!b1.IsTriggered && !b2.IsTriggered)
            return true;

        var colliding = NarrowPhase.MPREPA(sA, sB, b1.Orientation, b2.Orientation, b1.Position, b2.Position, out _, out _, out _, out _);
        if (colliding)
        {
            //sA.RigidBody.OnTriggerEnter();
            Console.WriteLine($"OnTriggerEnter ID:{sA.ShapeId} -> ID:{sB.ShapeId}");
        }

        return false;
    }
}

**Comment by captainkidd5** [comment]
This looks good to me

**Comment by notgiven688** [comment]
The idea is that this functionality should be implemented "on top" of Jitter - like you have shown already. I now implemented `NarrowPhase.Overlap(sA, sB, b1.Orientation, b2.Orientation, b1.Position, b2.Position)`, https://github.com/notgiven688/jitterphysics2/blob/78d5a1dee8144c210d068a44e6791f918616a0fe/src/Jitter2/Collision/NarrowPhase/NarrowPhase.cs#L960 which returns just true/false for overlaps and is therefore a bit more efficient than MPR which provides you with detailed collision information.
