### ISSUE TITLE
I hope the DebugDraw interface will be implemented soon.

### ISSUE THREAD

**Issue by CeSun** [notgiven688/jitterphysics2#37]
I'm using JitterPhysics on my toy game engine, it is awesome.
When using rigidbody with shape and raycast, if I can see the position of rigidbody/shape or the path of raycast, you can troubleshoot errors more intuitively.
For rays, if the path can be seen, it can also be clear in what state (such as rotation) the shape is detected.

**Comment by notgiven688** [comment]
Good point! I will start implementing RigidBody.DebugDraw(..). Which shapes do you mostly use?

**Comment by CeSun** [comment]
Thank you for your reply.
I mostly use ConvexHullShape, PointCloudShape and CapsuleShape.

**Comment by notgiven688** [comment]
Implemented in https://github.com/notgiven688/jitterphysics2/pull/40.
