### ISSUE TITLE
Callback function when entity transform changes.

### ISSUE THREAD

**Issue by CeSun** [notgiven688/jitterphysics2#38]
When the transform of an entity changes, is it possible to provide a callback function so that the transform of the corresponding entity in the game can be modified?

What I do now is: traverse every entity in the physical world every frame, find the corresponding game entity through Tag, and then modify the transform

**Comment by notgiven688** [comment]
Transformations (=Position and Orientation) of active bodies are likely to have changed since last frame. Enumerating through all active bodies can be done like so

```
        for (int i = 0; i < world.RigidBodies.Active; i++)
        {
            RigidBody ab = world.RigidBodies[i];
        }
```

**Comment by CeSun** [comment]
> Transformations (=Position and Orientation) of active bodies are likely to have changed since last frame. Enumerating through all active bodies can be done like so
> 
> ```
> for (int i = 0; i < world.RigidBodies.Active; i++)
> {
>     RigidBody ab = world.RigidBodies[i];
> }
> ```
I don't understand, when the rigid body state is modified, will his position in world.RigidBodies be moved to the front?

**Comment by notgiven688** [comment]
> I don't understand, when the rigid body state is modified, will his position in world.RigidBodies be moved to the front?

Yes, it will be moved in the active part of the list. See
https://github.com/notgiven688/jitterphysics2/blob/main/src/Jitter2/DataStructures/ActiveList.cs
