### ISSUE TITLE
Rigid body damping angular / linear is flipped

### ISSUE THREAD

**Issue by RonenNess** [notgiven688/jitterphysics2#53]
Check out this setter:

https://github.com/notgiven688/jitterphysics2/blob/e80205d51c3947efaf926d38c121800302be6ceb/src/Jitter2/Dynamics/RigidBody.cs#L189C1-L198C6

The setter call first param `angular` and second param `linear`, but when setting the values it set `linear` as first and `angular` as second, flipping them.

Looks like a mistake.

Also please add individual setter / getter for damping types. Thanks!

**Comment by notgiven688** [comment]
Fixed the reversal.

>Also please add individual setter / getter for damping types. 
This will not be implemented to avoid confusion (multiple ways of doing things).
