### ISSUE TITLE
Unity & NetStandard support?

### ISSUE THREAD

**Issue by JingchengYang4** [notgiven688/jitterphysics2#8]
I really want to use this in Unity but targeting at .Net 7 with C# > 7 makes it impossible. Jitter physics v1 works perfectly, is there any way you could make it compatible too?

**Comment by notgiven688** [comment]
Unfortunately Unity will not work with this engine at the moment. We use some modern language features which are necessary for good performance. In #9 I lowered the requirement to .Net 6 - this should at least work in godot now.

Unity has been gradually updating its support for newer versions of .NET and C#. It might be possible in the future that Unity will support a compatible version naturally, at which point the engine would become usable in Unity without modifications.

**Comment by JingchengYang4** [comment]
Ok, thank you for clarification, I will use v1 for now then.
